### ISSUE TITLE
Verion and release date it's outdated in the web and api

### ISSUE THREAD

**Issue by Marzal** [flathub/org.kde.falkon#10]
Follow up of comment https://github.com/flathub/org.kde.falkon/issues/5#issuecomment-1200439012

https://flathub.org/apps/details/org.kde.falkon shows
```
Updated : March 19, 2019
Version : 3.1.0
```
Installed app shows 22.04.3 and I do see that the builds are working
https://buildbot.flathub.org/#/apps/org.kde.falkon
so I would say that is a problem with the metadata (currentReleaseDate, currentReleaseVersion)

Looking in other repos some have file for this info
- https://github.com/flathub/org.filezillaproject.Filezilla/blob/master/org.filezillaproject.Filezilla.metainfo.xml
- https://github.com/flathub/org.filezillaproject.Filezilla/commit/0fc0ce7d9210eab44a87b7368290abb35bbea270

https://beta.flathub.org/es/apps/details/org.kde.okular
Okular doesn't have this files but the info is OK because it has in the sourced package
 `shell/org.kde.okular.appdata.xml:    <release version="22.04.3" date="2022-07-07"/>`

In Falkon sources I see
`linux/appdata/org.kde.falkon.appdata.xml:    <release version="22.04.3" date="2022-07-07"/>`

Probably useful documentation:
- https://flathub.org/api/v1/apps/org.kde.falkon
- https://github.com/flathub/website/commit/b4cd816211f26b87c12ff2b0223666d80153dfd4

**Comment by travier** [comment]
It's a "cosmetic" issue: https://invent.kde.org/network/falkon/-/commit/65e51dc54de31230066981c3c4d23efb193a0d6f

**Comment by Marzal** [comment]
> It's a "cosmetic" issue: https://invent.kde.org/network/falkon/-/commit/65e51dc54de31230066981c3c4d23efb193a0d6f

It was, thanks for the fast reply, I was just worried that some would see that info and think that the app was outdated/abandoned in flathub. Just "marketing".
I supposed that when there is a new build, it would be fixed on the frontend.

Thanks again Travier and Albert for your time.
