### ISSUE TITLE
3.2.0 unpublished

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/org.kde.falkon#5]
Hey, it looks like the latest [build](https://flathub.org/builds/#/builders/32/builds/81351) wasn't published:
```
TheEvilSkeleton@TheMainLaptop ~> flatpak search org.kde.falkon
Name        Description      Application ID      Version      Branch     Remotes
Falkon      Web Browser      org.kde.falkon      3.1.0        stable     flathub
```

Could you rebuild this? Hopefully it gets published.

**Comment by tsdgeos** [comment]
Built: https://flathub.org/builds/#/builders/32/builds/85937
Published: https://flathub.org/builds/#/builders/29/builds/46523

**Comment by Marzal** [comment]
Hi, I still see 3.1.0 when searching in flathub
![imagen](https://user-images.githubusercontent.com/2069735/182031626-082dd0e4-46e7-42bb-867f-f7782588fca6.png)

And https://flathub.org/apps/details/org.kde.falkon shows
```
Updated : March 19, 2019
Version : 3.1.0
```
![imagen](https://user-images.githubusercontent.com/2069735/182031664-46cb9db8-27c5-4a30-8459-370f2bf990c5.png)
